version: "3.8"

services:
   pocketbase:
      image: augustodelg/pocketbase
      container_name: pocketbase
      depends_on:
         - nginx
      ports:
         - "8090:8090"
      expose:
         - "8090"
      networks:
         - pocketbase
      volumes:
         - pocketbase:/pb_data

   nginx:
      image: "nginx"
      container_name: server
      ports:
         - "80:80"
         # volumes:
         #   - ./nginx.conf:/etc/nginx/nginx.conf
         # - ./default.conf:/etc/nginx/conf.d/
      expose:
         - "80"
      networks:
         - pocketbase
      # links:
      #   - pocketbase

volumes:
   pocketbase:

networks:
   pocketbase:
      driver: bridge
