version: "3.8"

services:
   pocketbase:
      image: spectado/pocketbase:latest
      container_name: pocketbase
      restart: unless-stopped
      depends_on:
         - server
      ports:
         - "8090:8090"
         - "801:80"
      expose:
         - "8090"
      networks:
         - pocketbase

   server:
      image: "jc21/nginx-proxy-manager:latest"
      restart: unless-stopped
      container_name: server
      ports:
         - "80:80"
         - "81:81"
         - "443:443"
      networks:
         - pocketbase
      volumes:
         - ./data:/data
         - ./letsencrypt:/etc/letsencrypt

volumes:
   pocketbase:


networks:
   pocketbase:
      driver: bridge
      name: lingoDeutsch
