version: "3.8"

services:
   pocketbase:
      image: augustodelg/pocketbase
      container_name: pocketbase
      depends_on:
         - nginx
      ports:
         - "8090:8090"
      expose:
         - "8090"
      networks:
         - pocketbase
      volumes:
         - pocketbase:/pb_data

   nginx:
      image: "nginx"
      container_name: server
      ports:
         - "80:80"
      expose:
         - "80"
      networks:
         - pocketbase
      volumes:
         - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
   pocketbase:

networks:
   pocketbase:
      driver: bridge
      name: flipycard_network
