export const types = {
   SET_CARDS: "SET_CARDS",
   CREATE_CARD: "CREATE_CARD",
   DELETE_CARD: "DELETE_CARD",
   SET_RANDOM_CARD: "SET_RANDOM_CARD",
   SET_CATEGORIES: "SET_CATEGORIES",
   CATEGORY_SELECTED: "CATEGORY_SELECTED",
   CATEGORY_ID: "CATEGORY_ID",
   CREATE_CATEGORY: "CREATE_CATEGORY",
   DELETE_CATEGORY: "DELETE_CATEGORY",
   SERVICE_ERROR: "SERVICE_ERROR"
}

export const constants = {
   CATEGORIES: "categories",
   CARDS: "cards",
   CATEGORY: "category"
}
